---
title: "Product Cost Change"
author: "Rising Eagle Construction LLC"
date: "`June 2023`"
output:
  html_document:
    code_folding: hide
    number_sections: true
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
library(ezids)
knitr::opts_chunk$set(echo = TRUE)
```

## Product Percentage change from 2020 to 2021



```{r }
library(readr)
library(ggplot2)

df <- read_csv('/Users/nusratprithee/Documents/Rising-Eagle-company-work/Purchase-History-with-Average-Unit-Price-2020-vs.-2021.csv')
columns_to_drop <- c("Type", "Qty Sold 01/01/21 to 12/31/21", "Sales $$ 01/01/21 to 12/31/21", "Qty Sold 01/01/20 to 12/31/20", "Sales $$ 01/01/20 to 12/31/20")
df <- df[, !(names(df) %in% columns_to_drop)]

# Convert the average unit price columns from strings to numeric values
df$`Average Unit Price 01/01/21 to 12/31/21` <- as.numeric(gsub("[$,]", "", df$`Average Unit Price 01/01/21 to 12/31/21`))
df$`Average Unit Price 01/01/20 to 12/31/20` <- as.numeric(gsub("[$,]", "", df$`Average Unit Price 01/01/20 to 12/31/20`))

# Calculate the percentage change
df$`Percentage Change` <- ((df$`Average Unit Price 01/01/21 to 12/31/21` - df$`Average Unit Price 01/01/20 to 12/31/20`) / df$`Average Unit Price 01/01/20 to 12/31/20`) * 100

# Create a bar chart
ggplot(df, aes(x = `Item #`, y = `Percentage Change`)) +
  geom_bar(stat = "identity", fill = "blue") +
  labs(x = "Item #", y = "Percentage Change", title = "Percentage Change of Average Unit Price (2020 to 2021)") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  geom_text(aes(label = sprintf("%.1f%%", `Percentage Change`)), vjust = -0.5, size = 3) +
  coord_cartesian(clip = "off") +
  theme(plot.margin = margin(1, 1, 1, 1, "cm"))

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
